services:
  # Backend service configuration
  - type: web
    name: my-app-backend
    env: node
    # Specify the build command if you have one, or you can leave it blank
    buildCommand: npm install --prefix backend
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
    # Add other environment variables as needed

  # Frontend service configuration
  - type: static-site
    name: my-app-frontend
    buildCommand: npm install --prefix frontend/falafellas && npm run build --prefix frontend/falafellas
    staticPublishPath: ./frontend/falafellas/build
    # Configure routes for client-side routing
    routes:
      - type: rewrite
        source: /**  # Matches all paths
        destination: /index.html  # Redirects to index.html for SPA routing
